feat(containerfiles): install 'hid-msi-claw'
kernel module and a related systemd service to force it into
'xinput' mode instead of 'desktop' mode.

diff --git a/containerfiles/stable b/containerfiles/stable
--- a/containerfiles/stable
+++ b/containerfiles/stable
@@ -4,24 +4,25 @@ FROM registry.playtron.one/internal/playtronos:1.0.0.13
 COPY rootfs/usr/lib/os-release-playtron /usr/lib/
 
 # Upgrade kernel.
+RUN rm -f /etc/yum.repos.d/negativo17-fedora-nvidia.repo
 RUN dnf remove -y kmod-nvidia* && \
   rpm-ostree override replace \
-  https://download.copr.fedorainfracloud.org/results/playtron/gaming/fedora-41-x86_64/09410114-kernel/kernel-6.15.8-203.nobara.fc41.x86_64.rpm \
-  https://download.copr.fedorainfracloud.org/results/playtron/gaming/fedora-41-x86_64/09410114-kernel/kernel-core-6.15.8-203.nobara.fc41.x86_64.rpm \
-  https://download.copr.fedorainfracloud.org/results/playtron/gaming/fedora-41-x86_64/09410114-kernel/kernel-devel-6.15.8-203.nobara.fc41.x86_64.rpm \
-  https://download.copr.fedorainfracloud.org/results/playtron/gaming/fedora-41-x86_64/09410114-kernel/kernel-devel-matched-6.15.8-203.nobara.fc41.x86_64.rpm \
-  https://download.copr.fedorainfracloud.org/results/playtron/gaming/fedora-41-x86_64/09410114-kernel/kernel-headers-6.15.8-203.nobara.fc41.x86_64.rpm \
-  https://download.copr.fedorainfracloud.org/results/playtron/gaming/fedora-41-x86_64/09410114-kernel/kernel-modules-6.15.8-203.nobara.fc41.x86_64.rpm
-# Rebuild NVIDIA drivers.
-RUN cp -r /etc/pam.d /etc/pam.d.bak; sed -i -r 's/^(session\s+required\s+pam_limits.so)/#\1/' /etc/pam.d/*; \
-  mkdir -p /run/akmods; \
-  for k in $(ls -1 /usr/src/kernels); do \
-    akmods --force --kernels "${k}" --kmod "nvidia" || exit 1; \
-    ls /var/cache/akmods/nvidia/*.failed.log > /dev/null 2>&1 && cat /var/cache/akmods/nvidia/*.failed.log || true; \
-    ls /usr/lib/modules/"${k}"/extra/nvidia/nvidia.ko.xz || exit 1; \
-  done; \
-  rm -rf /run/akmods; \
-  rm -rf /etc/pam.d; mv /etc/pam.d.bak /etc/pam.d;
+  https://download.copr.fedorainfracloud.org/results/playtron/gaming/fedora-41-x86_64/09784573-kernel/kernel-6.17.7-200.nobara.fc41.x86_64.rpm \
+  https://download.copr.fedorainfracloud.org/results/playtron/gaming/fedora-41-x86_64/09784573-kernel/kernel-core-6.17.7-200.nobara.fc41.x86_64.rpm \
+  https://download.copr.fedorainfracloud.org/results/playtron/gaming/fedora-41-x86_64/09784573-kernel/kernel-devel-6.17.7-200.nobara.fc41.x86_64.rpm \
+  https://download.copr.fedorainfracloud.org/results/playtron/gaming/fedora-41-x86_64/09784573-kernel/kernel-devel-matched-6.17.7-200.nobara.fc41.x86_64.rpm \
+  https://download.copr.fedorainfracloud.org/results/playtron/gaming/fedora-41-x86_64/09784573-kernel/kernel-headers-6.17.7-200.nobara.fc41.x86_64.rpm \
+  https://download.copr.fedorainfracloud.org/results/playtron/gaming/fedora-41-x86_64/09784573-kernel/kernel-modules-6.17.7-200.nobara.fc41.x86_64.rpm
+## Rebuild NVIDIA drivers.
+#RUN cp -r /etc/pam.d /etc/pam.d.bak; sed -i -r 's/^(session\s+required\s+pam_limits.so)/#\1/' /etc/pam.d/*; \
+#  mkdir -p /run/akmods; \
+#  for k in $(ls -1 /usr/src/kernels); do \
+#    akmods --force --kernels "${k}" --kmod "nvidia" || exit 1; \
+#    ls /var/cache/akmods/nvidia/*.failed.log > /dev/null 2>&1 && cat /var/cache/akmods/nvidia/*.failed.log || true; \
+#    ls /usr/lib/modules/"${k}"/extra/nvidia/nvidia.ko.xz || exit 1; \
+#  done; \
+#  rm -rf /run/akmods; \
+#  rm -rf /etc/pam.d; mv /etc/pam.d.bak /etc/pam.d;
 
 # https://github.com/playtron-os/rpm-specs-gaming
 RUN dnf5 -y upgrade \
@@ -29,7 +30,7 @@ RUN dnf5 -y upgrade \
   gamescope-session-0.1.0+319-1.fc41 \
   gamescope-session-playtron-0.4.1-1.fc41 \
   grid-1.24.0-1.fc40 \
-  inputplumber-0.67.0-0.fc41 \
+  inputplumber \
   legendary-0.20.41-1.playtron \
   libpact-0.3.0-1 \
   libplaytron-0.4.0-1 \
@@ -89,6 +90,20 @@ COPY rootfs/usr/libexec/playtron/nix-install /usr/libexec/playtron/nix-install
 RUN install -d -m 0755 /nix
 
 RUN dnf5 -y install snapd
+
+# Install Intel Claw 1 and 2 controller hack.
+COPY rootfs/usr/lib/systemd/system/intel-msi-claw.service    /usr/lib/systemd/system/
+COPY rootfs/usr/bin/intel-msi-claw    /usr/bin/
+## 'git' is also used to as part of the 'make install' step.
+RUN dnf5 -y install git
+RUN systemctl enable intel-msi-claw.service && \
+  git clone https://github.com/NeroReflex/hid-msi-claw-dkms.git /usr/src/hid-msi-claw && \
+  /bin/bash -c "cd /usr/src/hid-msi-claw && export TARGET=$(ls -1 /lib/modules | head -n 1) && make all && make install" && \
+  echo "hid_msi_claw" >> /usr/lib/modules-load.d/controllers.conf
+
+# Disable forced OS updates.
+RUN echo "VERSION_ID_ORIGINAL=$(grep VERSION_ID /usr/lib/os-release-playtron | cut -d= -f2)" >> /usr/lib/os-release-playtron && \
+  sed -i -E "s/VERSION_ID=.+/VERSION_ID=1.999.999.999/g" /usr/lib/os-release-playtron
 
 # View final packages.
 RUN rpm -qa | sort
